### ISSUE TITLE
Docker image not found on private registry

### ISSUE THREAD

**Issue by JacopoDaeli** [remind101/empire#674] opened 2015-10-13 15:28 UTC
Hello guys,

I've just setted my private docker registry `https://docker-registry.impero.me/v2/`. 

Manually from docker it works fine, but when I use it in the Empire stack config, and I try to deploy an image, for example 

```sh
bin $ ./emp deploy docker-registry.impero.me/impero/nginx
```

I get 
```sh
Pulling repository impero/nginx
error: Error: image impero/nginx:latest not found
```

Can  someone help me out? Also I don't understand how to setup the login with GitHub. But this is another topic so I may create a dedicated issue.

**Comment by phobologic** [comment] 2015-10-13 16:38
Hey @JacopoDaeli - this appears to be a duplicate of: https://github.com/remind101/empire/issues/624

This is definitely something I hope we'll be able to fix soon.

**Closed by phobologic** 2015-10-13 16:38 UTC
