### ISSUE TITLE
Authenticating empire to use our ECR registries?

### ISSUE THREAD

**Issue by igrayson** [remind101/empire#856] opened 2016-05-27 16:29 UTC
Hi team,

I just stood up the demo cloudformation stack, and so far it looks very cool.

I'm trying to deploy an image from a private ECR repo, under the same account.

My `emp deploy awsaccountid.dkr.ecr.us-west-2.amazonaws.com/myimage:tag` command fails with: `error: Authentication is required.`.

I've read https://github.com/remind101/empire/issues/703, and I can see that the container's instance profile has those permissions; it looks like the cloudformation script automatically included it in the `ecs` policy of `empire-InstanceRole-1JYI42LLKKDKJ`.

Is there some other configuration that's required?

**Comment by igrayson** [comment] 2016-05-27 16:35
If it helps, here's the log snippet:

```
t=2016-05-27T16:32:20+0000 lvl=info msg=request.start request_id= method=GET path=/health
t=2016-05-27T16:32:20+0000 lvl=info msg=request.complete request_id= status=200
t=2016-05-27T16:32:37+0000 lvl=info msg=request.start request_id=1289d50e-b980-4bd2-afd5-ecfdeda71572 method=POST path=/deploys
t=2016-05-27T16:32:37+0000 lvl=info msg=authenticated request_id=1289d50e-b980-4bd2-afd5-ecfdeda71572 user=igrayson
t=2016-05-27T16:32:39+0000 lvl=info msg=PullImage request_id=1289d50e-b980-4bd2-afd5-ecfdeda71572 trace.id=691dc3be-9b35-4c7b-82da-fa74e159c681 trace.parent= trace.func=github.com/remind101/empire/pkg/dockerutil.(*Client).PullImage trace.file=/go/src/github.com/remind101/empire/pkg/dockerutil/client.go trace.line=81 trace.duration=1.184377419s registry= repository=MY_ECR_REPO tag=git-6e3804f
t=2016-05-27T16:32:39+0000 lvl=info msg=request.complete request_id=1289d50e-b980-4bd2-afd5-ecfdeda71572 status=0
t=2016-05-27T16:32:49+0000 lvl=info msg=request.start request_id= method=GET path=/health
t=2016-05-27T16:32:49+0000 lvl=info msg=request.complete request_id= status=200
t=2016-05-27T16:32:50+0000 lvl=info msg=request.start request_id= method=GET path=/health
t=2016-05-27T16:32:50+0000 lvl=info msg=request.complete request_id= status=200
```

I'd be happy to suggest documentation updates afterwards, if I can.

**Comment by igrayson** [comment] 2016-05-27 17:23
In case it mattered, I tried putting an image in a `us-east-1` ECR registry, with the same result.

**Comment by protomouse** [comment] 2016-05-27 22:46
@igrayson Empire's logic for decoding image references ([source](https://github.com/remind101/empire/blob/5facae771b03e976e6d68437f86bdb6f6ef705c1/pkg/image/image.go#L122)) is sort of basic. It doesn't behave like the Docker CLI, which uses regular expressions ([grammar](https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/vendor/src/github.com/docker/distribution/reference/reference.go)). I'd consider this a bug.

A workaround for you is to prefix the repository in ECR so that the full reference contains at least two slashes. We (by design) use environment specifiers, e.g. `prod/myimage:tag`.

**Comment by igrayson** [comment] 2016-05-27 22:51
I'm not sure I follow.

Do you have an example of a full `awsaccountid.dkr.ecr...` image name:tag that works with empire's ECR  logic?

I think I understood your reply to mean I should try an ECR repository named `my/service` instead of `my-service`?

**Comment by protomouse** [comment] 2016-05-27 22:53
`awsaccountid.dkr.ecr.us-west-2.amazonaws.com/igrayson/myimage:tag`, for instance, should work.

**Comment by igrayson** [comment] 2016-05-27 22:54
That works 👍 

I'll look for a place this could be documented.

**Comment by protomouse** [comment] 2016-05-27 23:32
I went ahead and opened a separate issue for this (#857).

**Comment by igrayson** [comment] 2016-05-28 09:10
Should it be marked as a bug, and discuss the impact on our ECR support?

**Comment by ejholmes** [comment] 2016-06-08 00:32
Gonna go ahead and close this in favor of https://github.com/remind101/empire/issues/857.

**Closed by ejholmes** 2016-06-08 00:32 UTC
